services:
  backend:
    build: ./src/backend/
    ports:
      - "8000:8000"
  frontend:
    build: ./src/frontend 
    ports:
      - "3000:3000"
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=secret
    volumes:
      - ./data:/var/lib/postgresql/data
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

