services:
  backend:
    build: ./src/backend/
    ports:
      - "8000:8000"
  frontend:
    build: ./src/frontend
    ports:
      - "80:3000"
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=shourya
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo_app
    volumes:
      - ./data:/var/lib/postgresql/data
